// 🔷 Baza danych haseł
const bazaDanych = {
  klasyczne: {
     Powiedzenia: [
  "Co nagle to po diable",
  "Lepszy wrobel w garsci niz golab na dachu",
  "Kto pod kim dolki kopie sam w nie wpada",
  "Jak sobie poscielesz tak sie wyspisz",
  "Madry Polak po szkodzie",
  "Nie chwal dnia przed zachodem slonca",
  "Darowanemu koniowi w zeby sie nie zaglada",
  "Gdzie kucharek szesc tam nie ma co jesc",
  "Cicha woda brzegi rwie",
  "Kto rano wstaje temu Pan Bog daje",
  "Nie wszystko zloto co sie swieci",
  "Z duzej chmury maly deszcz",
  "Nie dziel skory na niedzwiedziu",
  "Gdyby kozka nie skakala to by nozki nie zlamala",
  "Jak cie widza tak cie pisza",
  "Kto pyta nie bladzi",
  "Nie taki diabel straszny jak go maluja",
  "Gdzie dwoch sie bije tam trzeci korzysta",
  "Kto nie ryzykuje nie pije szampana",
  "Z proznego i Salomon nie naleje",
  "Nie ma dymu bez ognia",
  "Kto mieczem wojuje od miecza ginie",
  "Jak Kuba Bogu tak Bog Kubie",
  "Czego Jas sie nie nauczy tego Jan nie bedzie umial",
  "Gdzie drwa rabia tam wiory leca",
  "Nie wchodzi sie dwa razy do tej samej rzeki",
  "Kto ma pszczoly ten ma miod",
  "Nie igraj z ogniem",
  "Nie wywoluj wilka z lasu",
  "Nie rob drugiemu co tobie niemile",
  "Nie swieci garnki lepia",
  "Nie ma co plakac nad rozlanym mlekiem",
  "Nie kijem go to palka",
  "Nie czas zalowac roz gdy plona lasy",
  "Jak trwoga to do Boga",
  "Krowa ktora duzo ryczy malo mleka daje",
  "Glodnemu chleb na mysli",
  "Kto sie smieje ostatni ten sie smieje najlepiej",
  "Zlapac Pana Boga za nogi",
  "Nie ucz ojca dzieci robic",
  "Nie ma tego zlego co by na dobre nie wyszlo",
  "Jak Kuba Bogu tak Bog Kubie",
  "Kto pod kim dolki kopie sam w nie wpada",
  "Gdzie kucharek szesc tam nie ma co jesc",
  "Kto pyta nie bladzi",
  "Jak cie widza tak cie pisza",
  "Nie taki diabel straszny jak go maluja",
  "Nie ma rozy bez kolcow",
  "Nie ma dymu bez ognia",
  "Nie ma co plakac nad rozlanym mlekiem",
  "Nie ma tego zlego co by na dobre nie wyszlo",
  "Nie ma jak w domu",
  "Nie ma co sie przejmowac",
  "Kto rano wstaje temu Pan Bog daje",
  "Jak sobie poscielesz tak sie wyspisz",
  "Gdzie dwoch sie bije tam trzeci korzysta",
  "Kto mieczem wojuje od miecza ginie",
  "Nie dziel skory na niedzwiedziu",
  "Z duzej chmury maly deszcz",
  "Nie wszystko zloto co sie swieci",
  "Cicha woda brzegi rwie",
  "Darowanemu koniowi w zeby sie nie zaglada",
  "Madry Polak po szkodzie",
  "Co nagle to po diable",
  "Lepszy wrobel w garsci niz golab na dachu",
  "Jak trwoga to do Boga",
  "Nie ucz ojca dzieci robic",
  "Z proznego i Salomon nie naleje",
  "Gdyby kozka nie skakala to by nozki nie zlamala",
  "Nie swieci garnki lepia",
  "Nie rob drugiemu co tobie niemile",
  "Nie igraj z ogniem",
  "Nie wywoluj wilka z lasu",
  "Kto nie ryzykuje nie pije szampana",
  "Jak Kuba Bogu tak Bog Kubie",
  "Czego Jas sie nie nauczy tego Jan nie bedzie umial",
  "Gdzie drwa rabia tam wiory leca",
  "Nie wchodzi sie dwa razy do tej samej rzeki",
  "Kto ma pszczoly ten ma miod",
  "Krowa ktora duzo ryczy malo mleka daje",
  "Glodnemu chleb na mysli",
  "Kto sie smieje ostatni ten sie smieje najlepiej",
  "Zlapac Pana Boga za nogi",
  "Nie kijem go to palka",
  "Nie czas zalowac roz gdy plona lasy",
  "Nie ma co sie przejmowac",
  "Nie ma jak w domu",
  "Nie ma tego zlego co by na dobre nie wyszlo",
  "Nie ma co plakac nad rozlanym mlekiem",
  "Nie ma dymu bez ognia",
  "Nie ma rozy bez kolcow",
  "Nie taki diabel straszny jak go maluja",
  "Jak cie widza tak cie pisza",
  "Kto pyta nie bladzi",
  "Gdzie kucharek szesc tam nie ma co jesc",
  "Kto pod kim dolki kopie sam w nie wpada",
  "Jak Kuba Bogu tak Bog Kubie",
  "Co nagle to po diable",
  "Lepszy wrobel w garsci niz golab na dachu"
],
    Filmy: [
  "Ojciec chrzestny",
  "Matrix",
  "Titanic",
  "Skazani na Shawshank",
  "Forrest Gump",
  "Pulp Fiction",
  "Incepcja",
  "Gladiator",
  "Zielona mila",
  "Fight Club",
  "Lista Schindlera",
  "Czlowiek z blizna",
  "Milczenie owiec",
  "Interstellar",
  "Django",
  "Requiem dla snu",
  "American Beauty",
  "Czarny labedz",
  "Wladca Pierscieni Drużyna Pierscienia",
  "Wladca Pierscieni Dwie wieze",
  "Wladca Pierscieni Powrot krola",
  "Gwiezdne wojny Nowa nadzieja",
  "Gwiezdne wojny Imperium kontratakuje",
  "Gwiezdne wojny Powrot Jedi",
  "Gwiezdne wojny Przebudzenie Mocy",
  "Gwiezdne wojny Ostatni Jedi",
  "Harry Potter i Kamien Filozoficzny",
  "Harry Potter i Komnata Tajemnic",
  "Harry Potter i Wiezien Azkabanu",
  "Harry Potter i Czara Ognia",
  "Harry Potter i Zakon Feniksa",
  "Harry Potter i Ksiaze Polkrwi",
  "Harry Potter i Insygnia Smierci czesc pierwsza",
  "Harry Potter i Insygnia Smierci czesc druga",
  "Avengers",
  "Avengers Czas Ultrona",
  "Avengers Wojna bez granic",
  "Avengers Koniec gry",
  "Iron Man",
  "Iron Man dwa",
  "Iron Man trzy",
  "Kapitan Ameryka Pierwsze starcie",
  "Kapitan Ameryka Zimowy zolnierz",
  "Kapitan Ameryka Wojna bohaterow",
  "Thor",
  "Thor Mroczny swiat",
  "Thor Ragnarok",
  "Thor Milosc i grom",
  "Spider Man",
  "Spider Man dwa",
  "Spider Man trzy",
  "Spider Man Homecoming",
  "Spider Man Daleko od domu",
  "Spider Man Bez drogi do domu",
  "Batman",
  "Batman Poczatek",
  "Mroczny Rycerz",
  "Mroczny Rycerz powstaje",
  "Joker",
  "Deadpool",
  "Deadpool dwa",
  "Logan",
  "X Men",
  "X Men dwa",
  "X Men Ostatni bastion",
  "X Men Pierwsza klasa",
  "X Men Przeszlosc ktora nadejdzie",
  "X Men Apokalipsa",
  "X Men Mroczna Phoenix",
  "Straznicy Galaktyki",
  "Straznicy Galaktyki vol dwa",
  "Straznicy Galaktyki vol trzy",
  "Doktor Strange",
  "Doktor Strange w multiwersum obledu",
  "Ant Man",
  "Ant Man i Osa",
  "Ant Man i Osa Kwantomania",
  "Czarna Pantera",
  "Czarna Pantera Wakanda w moim sercu",
  "Kapitan Marvel",
  "Shazam",
  "Aquaman",
  "Wonder Woman",
  "Wonder Woman tysiac dziewiecset osiemdziesiat cztery",
  "Flash",
  "Suicide Squad",
  "Legion samobojcow",
  "Venom",
  "Venom Carnage",
  "Morbius",
  "Transformers",
  "Transformers Zemsta upadlych",
  "Transformers Ciemna strona ksiezyca",
  "Transformers Wiek zaglady",
  "Transformers Ostatni rycerz",
  "Transformers Przebudzenie bestii",
  "Szybcy i wsciekli",
  "Szybcy i wsciekli dwa",
  "Szybcy i wsciekli Tokio Drift",
  "Szybcy i wsciekli piec",
  "Szybcy i wsciekli szesc",
  "Szybcy i wsciekli siedem",
  "Szybcy i wsciekli osiem",
  "Szybcy i wsciekli dziewiec",
  "Szybcy i wsciekli dziesiec"
],
    Gry: [
  "Wiedźmin",
  "Minecraft",
  "Counter Strike",
  "League of Legends",
  "Fortnite",
  "Call of Duty",
  "Assassins Creed",
  "Grand Theft Auto",
  "Red Dead Redemption",
  "The Elder Scrolls",
  "World of Warcraft",
  "Hearthstone",
  "Overwatch",
  "Diablo",
  "Starcraft",
  "Cyberpunk",
  "Baldurs Gate",
  "FIFA",
  "NBA Live",
  "Pro Evolution Soccer",
  "Need for Speed",
  "The Sims",
  "SimCity",
  "Civilization",
  "Age of Empires",
  "Command and Conquer",
  "Heroes of Might and Magic",
  "Total War",
  "Doom",
  "Quake",
  "Half Life",
  "Portal",
  "Left 4 Dead",
  "Team Fortress",
  "Far Cry",
  "Crysis",
  "Battlefield",
  "Mass Effect",
  "Dragon Age",
  "The Witcher",
  "Fallout",
  "Skyrim",
  "Oblivion",
  "Morrowind",
  "Dark Souls",
  "Elden Ring",
  "Sekiro",
  "Bloodborne",
  "Hades",
  "Stardew Valley",
  "Terraria",
  "Don't Starve",
  "RimWorld",
  "Factorio",
  "Cities Skylines",
  "Euro Truck Simulator",
  "American Truck Simulator",
  "Flight Simulator",
  "Microsoft Solitaire",
  "Candy Crush Saga",
  "Angry Birds",
  "Clash of Clans",
  "Clash Royale",
  "Brawl Stars",
  "PUBG",
  "Apex Legends",
  "Valorant",
  "Roblox",
  "Among Us",
  "Tetris",
  "Pac Man",
  "Super Mario Bros",
  "Mario Kart",
  "Luigis Mansion",
  "Zelda Breath of the Wild",
  "Zelda Tears of the Kingdom",
  "Metroid",
  "Kirby",
  "Donkey Kong",
  "Animal Crossing",
  "Fire Emblem",
  "Bayonetta",
  "Splatoon",
  "Pikmin",
  "Monster Hunter",
  "Resident Evil",
  "Silent Hill",
  "Metal Gear Solid",
  "Final Fantasy",
  "Kingdom Hearts",
  "Persona",
  "Yakuza",
  "Nier Automata",
  "Ghost of Tsushima",
  "Horizon Zero Dawn",
  "Horizon Forbidden West",
  "Death Stranding",
  "Ratchet and Clank",
  "Jak and Daxter",
  "Crash Bandicoot",
  "Spyro the Dragon",
  "Little Big Planet",
  "Uncharted",
  "The Last of Us"
],
    Serial: [
  "Gra o tron",
  "Breaking Bad",
  "Stranger Things",
  "Dom z papieru",
  "Czarne lustro",
  "Sherlock",
  "Peaky Blinders",
  "The Office",
  "Przyjaciele",
  "Jak poznałem waszą matkę",
  "Teoria wielkiego podrywu",
  "Better Call Saul",
  "Narcos",
  "Vikings",
  "Wikingowie Walhalla",
  "The Crown",
  "House of Cards",
  "Ozark",
  "Mindhunter",
  "Dexter",
  "Dexter Nowa krew",
  "Lost",
  "Zagubieni",
  "24 godziny",
  "Skazany na śmierć",
  "Dr House",
  "Chirurdzy",
  "Grey Anatomy",
  "The Good Doctor",
  "Chicago Med",
  "Chicago Fire",
  "Chicago PD",
  "CSI Kryminalne zagadki Miami",
  "CSI Kryminalne zagadki Nowego Jorku",
  "CSI Kryminalne zagadki Las Vegas",
  "NCIS",
  "NCIS Los Angeles",
  "NCIS Hawaje",
  "Mentalista",
  "Elementary",
  "Bones",
  "Castle",
  "Lucifer",
  "Supernatural",
  "The Walking Dead",
  "Fear the Walking Dead",
  "The Last of Us",
  "The Mandalorian",
  "Obi Wan Kenobi",
  "Ahsoka",
  "Andor",
  "Star Wars Rebelianci",
  "Star Wars Wojny klonów",
  "Wiedźmin",
  "Wiedźmin Rodowód krwi",
  "Shadow and Bone",
  "The Witcher Blood Origin",
  "The Boys",
  "Gen V",
  "Invincible",
  "Titans",
  "Doom Patrol",
  "Arrow",
  "Flash",
  "Supergirl",
  "Legends of Tomorrow",
  "Smallville",
  "Gotham",
  "Pennyworth",
  "The Umbrella Academy",
  "The Haunting of Hill House",
  "The Haunting of Bly Manor",
  "Midnight Mass",
  "You",
  "Ty",
  "Riverdale",
  "Sabrina",
  "Sex Education",
  "Heartstopper",
  "Elite",
  "Trzynaście powodów",
  "Dark",
  "1899",
  "Barwy szczęścia",
  "M jak miłość",
  "Na dobre i na złe",
  "Ojciec Mateusz",
  "Ranczo",
  "Świat według Kiepskich",
  "Klan",
  "Pierwsza miłość",
  "Złotopolscy",
  "Wataha",
  "Belfer",
  "Król",
  "Stulecie Winnych",
  "Dziewczyny ze Lwowa",
  "Szadź",
  "Behawiorysta",
  "Znachor",
  "Wilk",
  "Nielegalni",
  "Pułapka"
],
    Historia: [
  "Napoleon Bonaparte",
  "Maria Sklodowska Curie",
  "Jozef Pilsudski",
  "Kazimierz Wielki",
  "Mieszko Pierwszy",
  "Unia Lubelska",
  "Rozbiory Polski",
  "Powstanie listopadowe",
  "Powstanie styczniowe",
  "Konstytucja Trzeciego Maja",
  "Zamach majowy",
  "Solidarnosc",
  "Stan wojenny",
  "Okragly stol",
  "Lech Walesa",
  "Wojna trzydziestoletnia",
  "Rewolucja francuska",
  "Rewolucja pazdziernikowa",
  "Wielka rewolucja przemyslowa",
  "Wojna secesyjna",
  "Bitwa pod Grunwaldem",
  "Bitwa pod Wiedniem",
  "Bitwa pod Monte Cassino",
  "Bitwa pod Stalingradem",
  "Bitwa pod Waterloo",
  "Bitwa o Anglie",
  "Bitwa o Berlin",
  "Bitwa o Normandie",
  "Bitwa o Iwo Jima",
  "Bitwa o Midway",
  "Traktat pokojowy z Niemcami",
  "Traktat pokojowy z Japonia",
  "Traktat pokojowy z Austro Wegrami",
  "Traktat pokojowy z Wlochami",
  "Traktat pokojowy z Rosja",
  "Pakt Ribbentrop Molotow",
  "Konferencja w Jalcie",
  "Konferencja w Teheranie",
  "Konferencja w Poczdamie",
  "Traktat wersalski",
  "Traktat w Tylzy",
  "Traktat w Saint Germain",
  "Traktat w Sevres",
  "Traktat w Locarno",
  "Traktat w Monachium",
  "Traktat w Maastricht",
  "Traktat lizbonski",
  "Wojna peloponeska",
  "Wojna stuletnia",
  "Wojna krymska",
  "Wojna rosyjsko japonska",
  "Wojna domowa w Rosji",
  "Wojna domowa w Hiszpanii",
  "Wojna wietnamska",
  "Wojna w Korei",
  "Wojna w Afganistanie",
  "Wojna w Iraku",
  "Wojna w Syrii",
  "Wojna w Ukrainie",
  "Zimna wojna",
  "Bitwa pod Hastings",
  "Bitwa pod Trafalgarem",
  "Bitwa pod Lepanto",
  "Bitwa pod Azincourt",
  "Bitwa o Kursk",
  "Bitwa o Moskwa",
  "Bitwa o Leningrad",
  "Bitwa o Arnhem",
  "Bitwa o Prage",
  "Wielka emigracja",
  "Powstanie warszawskie",
  "Powstanie wielkopolskie",
  "Powstanie slaskie",
  "Bitwa narodow",
  "Rozstrzelanie w Katyniu",
  "Zbrodnia wołyńska",
  "Zamach na arcyksiecia Ferdynanda",
  "Wielki glod na Ukrainie",
  "Holokaust",
  "Procesy norymberskie",
  "Deklaracja niepodleglosci USA",
  "Deklaracja praw czlowieka",
  "Manifest komunistyczny",
  "Upadek muru berlinskiego",
  "Rozpad ZSRR",
  "Zjednoczenie Niemiec",
  "Rozpad Jugoslawii",
  "Zamach na Kennedyego",
  "Zamach na Jana Pawla Drugiego",
  "Zamach na World Trade Center",
  "Kryzys kubański",
  "Kryzys sueski",
  "Kryzys migracyjny",
  "Kryzys klimatyczny",
  "Kryzys gospodarczy",
  "Wielka depresja",
  "Plan Marshalla",
  "Plan Balcerowicza",
  "Wejscie Polski do NATO",
  "Wejscie Polski do Unii Europejskiej",
  "Pierwsze wolne wybory",
  "Obalenie komunizmu",
  "Strajki w Stoczni Gdanskiej",
  "Porozumienia sierpniowe",
  "Stanowienie demokracji",
  "Rozpad monarchii absolutnej",
  "Poczatki parlamentaryzmu",
  "Rozwoj kapitalizmu",
  "Era odkryc geograficznych"
],
    Geografia: [
  "Sahara",
  "Amazonka",
  "Mount Everest",
  "Nil",
  "Andy",
  "Kilimandżaro",
  "Ganges",
  "Missisipi",
  "Alpy",
  "Tatry",
  "Bałtyk",
  "Morze Czarne",
  "Morze Śródziemne",
  "Morze Północne",
  "Morze Karaibskie",
  "Morze Japońskie",
  "Morze Martwe",
  "Morze Kaspijskie",
  "Morze Beringa",
  "Morze Barentsa",
  "Rzeka Wisła",
  "Rzeka Odra",
  "Rzeka Dunaj",
  "Rzeka Loara",
  "Rzeka Ren",
  "Rzeka Sekwana",
  "Rzeka Tyber",
  "Rzeka Tamiza",
  "Rzeka Huang He",
  "Rzeka Jangcy",
  "Rzeka Mekong",
  "Rzeka Kongo",
  "Rzeka Lena",
  "Rzeka Wołga",
  "Rzeka Eufrat",
  "Rzeka Tygrys",
  "Rzeka Indus",
  "Rzeka Colorado",
  "Rzeka Jukon",
  "Rzeka Murray",
  "Góry Skaliste",
  "Góry Atlas",
  "Góry Ural",
  "Góry Apeniny",
  "Góry Pireneje",
  "Góry Dynarskie",
  "Góry Kaukaz",
  "Góry Harz",
  "Góry Sudety",
  "Góry Karpaty",
  "Wyżyna Krakowsko Częstochowska",
  "Wyżyna Lubelska",
  "Wyżyna Śląska",
  "Wyżyna Małopolska",
  "Wyżyna Brazylijska",
  "Wyżyna Meksykańska",
  "Wyżyna Tybetańska",
  "Wyżyna Deccan",
  "Wyżyna Kolorado",
  "Nizina Mazowiecka",
  "Nizina Wielkopolska",
  "Nizina Śląska",
  "Nizina Francuska",
  "Nizina Niemiecka",
  "Nizina Węgierska",
  "Nizina Gangesu",
  "Nizina Amazonki",
  "Nizina Chińska",
  "Nizina Zachodniosyberyjska",
  "Nizina Wschodnioeuropejska",
  "Pustynia Gobi",
  "Pustynia Atakama",
  "Pustynia Kalahari",
  "Pustynia Namib",
  "Pustynia Ar-Rub al-Chali",
  "Pustynia Mojave",
  "Pustynia Negew",
  "Pustynia Sonora",
  "Pustynia Thar",
  "Pustynia Simpson",
  "Jezioro Bajkał",
  "Jezioro Wiktorii",
  "Jezioro Tanganika",
  "Jezioro Titicaca",
  "Jezioro Michigan",
  "Jezioro Huron",
  "Jezioro Erie",
  "Jezioro Ontario",
  "Jezioro Genewskie",
  "Jezioro Bodeńskie",
  "Archipelag Malajski",
  "Archipelag Filipiński",
  "Archipelag Svalbard",
  "Archipelag Galapagos",
  "Archipelag Hawajski",
  "Wyspa Madagaskar",
  "Wyspa Borneo",
  "Wyspa Sumatra",
  "Wyspa Islandia",
  "Wyspa Nowa Gwinea"
],
    Fantastyka: [
  "Wladca Pierscieni Drużyna Pierscienia",
  "Wladca Pierscieni Dwie wieze",
  "Wladca Pierscieni Powrot krola",
  "Wladca Pierscieni Hobbit Niezwykla podroz",
  "Wladca Pierscieni Hobbit Pustkowie Smauga",
  "Harry Potter Kamien Filozoficzny",
  "Harry Potter Komnata Tajemnic",
  "Harry Potter Wiezien Azkabanu",
  "Harry Potter Czara Ognia",
  "Harry Potter Zakon Feniksa",
  "Star Wars Nowa nadzieja",
  "Star Wars Imperium kontratakuje",
  "Star Wars Powrot Jedi",
  "Star Wars Przebudzenie Mocy",
  "Star Wars Ostatni Jedi",
  "Gra o tron",
  "Rod smoka",
  "Opowiesci z Narnii Lew czarownica i stara szafa",
  "Opowiesci z Narnii Ksiezniczka i jezdziec",
  "Opowiesci z Narnii Podroz Wedrowca do Switu",
  "Zwiadowcy Ruiny Gorlanu",
  "Zwiadowcy Plonacy most",
  "Zwiadowcy Ziemia skuta lodem",
  "Zwiadowcy Bitwa o Skandie",
  "Zwiadowcy Czarnoksiężnik z Północy",
  "Percy Jackson Zlodziej pioruna",
  "Percy Jackson Morze potworow",
  "Percy Jackson Klątwa tytana",
  "Percy Jackson Bitwa w Labiryncie",
  "Percy Jackson Ostatni Olimpijczyk",
  "Igrzyska smierci",
  "W pierścieniu ognia",
  "Kosoglos",
  "Ballada ptakow i wezy",
  "Zmierzch",
  "Ksiezyc w nowiu",
  "Zaćmienie",
  "Przed świtem",
  "Eragon",
  "Najstarszy",
  "Brisingr",
  "Dziedzictwo",
  "Diuna",
  "Mesjasz Diuny",
  "Dzieci Diuny",
  "Bóg Imperator Diuny",
  "Heretycy Diuny",
  "Łowcy Diuny",
  "Fundacja",
  "Fundacja i Imperium",
  "Druga Fundacja",
  "Fundacja na skraju",
  "Fundacja i Ziemia",
  "Metro dwadziescia trzy",
  "Metro dwadziescia cztery",
  "Metro dwadziescia piec",
  "Wiedźmin Ostatnie zyczenie",
  "Wiedźmin Miecz przeznaczenia",
  "Wiedźmin Krew elfow",
  "Wiedźmin Czas pogardy",
  "Wiedźmin Chrzest ognia",
  "Wiedźmin Wieża jaskółki",
  "Wiedźmin Pani jeziora",
  "Wiedźmin Sezon burz",
  "Mroczne materie Zorza polarna",
  "Mroczne materie Magiczny noz",
  "Mroczne materie Bursztynowa luneta",
  "Z mgly zrodzony",
  "Studnia wstapienia",
  "Bohater wiekow",
  "Cienie tozsamosci",
  "Zlamany tron",
  "Czarny Pryzmat",
  "Oślepiający nóż",
  "Złodziej światła",
  "Cień doskonały",
  "Kroniki Shannary",
  "Mag bitewny",
  "Czarnoksiężnik z Archipelagu",
  "Grobowce Atuanu",
  "Najdalszy brzeg",
  "Tehanu",
  "Opowieści o Terramarze",
  "Mroczne umysły",
  "Dzień zero",
  "Po zmierzchu",
  "Czerwone jak krew",
  "Białe jak śnieg",
  "Czarne jak heban",
  "Zakon smoka",
  "Zakon cienia",
  "Zakon ognia",
  "Zakon lodu",
  "Zakon burzy",
  "Mitologia nordycka",
  "Mitologia grecka",
  "Mitologia egipska",
  "Mitologia slowianska",
  "Mitologia celtycka",
  "Potwory i demony",
  "Elfy i krasnoludy",
  "Smoki i wilkolaki",
  "Magia i miecz",
  "Czarodzieje i zaklecia",
  "Portale i wymiary",
  "Apokalipsa i proroctwa",
  "Przestrzen kosmiczna",
  "Podziemne miasta",
  "Zaginione cywilizacje"
],
    Nauka: [
  "Grawitacja",
  "Fotosynteza",
  "Ewolucja",
  "Komorka",
  "Atom",
  "Czasteczka",
  "DNA",
  "RNA",
  "Mutacja",
  "Genotyp",
  "Fenotyp",
  "Chlorofil",
  "Mitochondrium",
  "Jadro komorkowe",
  "Bialko",
  "Enzym",
  "Reakcja chemiczna",
  "Wiazanie chemiczne",
  "Pierwiastek",
  "Izotop",
  "Kwasy",
  "Zasady",
  "Sole",
  "Roztwor",
  "Stala gazowa",
  "Prawo Archimedesa",
  "Prawo Pascala",
  "Prawo Ohma",
  "Prawo Boyle'a",
  "Prawo Hooke'a",
  "Teoria względności",
  "Teoria ewolucji",
  "Teoria strun",
  "Teoria chaosu",
  "Teoria komorkowa",
  "Zasada nieoznaczonosci",
  "Zasada zachowania energii",
  "Zasada zachowania pędu",
  "Zasada superpozycji",
  "Zasada działania dźwigni",
  "Siła",
  "Masa",
  "Energia",
  "Praca",
  "Moc",
  "Temperatura",
  "Cisnienie",
  "Predkosc",
  "Przyspieszenie",
  "Opór",
  "Napięcie",
  "Natężenie",
  "Obwód elektryczny",
  "Pole magnetyczne",
  "Indukcja elektromagnetyczna",
  "Fale elektromagnetyczne",
  "Promieniowanie",
  "Spektrum",
  "Soczewka",
  "Zwrcadlo",
  "Refleksja",
  "Refrakcja",
  "Dyfrakcja",
  "Interferencja",
  "Grawitacja",
  "Orbita",
  "Galaktyka",
  "Gwiazda",
  "Planeta",
  "Ksiezyc",
  "Kometa",
  "Asteroida",
  "Meteor",
  "Czarna dziura",
  "Supernowa",
  "Kosmos",
  "Wszechswiat",
  "Big Bang",
  "Układ słoneczny",
  "Ziemia",
  "Skorupa ziemska",
  "Plaszcz ziemski",
  "Jadro ziemi",
  "Wulkan",
  "Trzesienie ziemi",
  "Plyty tektoniczne",
  "Erozja",
  "Sedimentacja",
  "Skala Mohsa",
  "Minerał",
  "Skała",
  "Fotosynteza",
  "Oddychanie komorkowe",
  "Fermentacja",
  "Układ nerwowy",
  "Układ krwionośny",
  "Układ oddechowy",
  "Układ pokarmowy",
  "Układ wydalniczy",
  "Neuron",
  "Synapsa",
  "Hormon",
  "Enzym",
  "Receptor",
  "Algorytm",
  "Programowanie",
  "Sztuczna inteligencja",
  "Uczenie maszynowe",
  "Sieci neuronowe"
],
    Muzyka: [
  "Melodia",
  "Rytm",
  "Tempo",
  "Dynamika",
  "Harmonia",
  "Tonacja",
  "Skala molowa",
  "Skala durowa",
  "Skala pentatoniczna",
  "Skala chromatyczna",
  "Akord",
  "Interwal",
  "Kontrapunkt",
  "Polifonia",
  "Monodia",
  "Instrumenty strunowe",
  "Instrumenty dęte",
  "Instrumenty perkusyjne",
  "Instrumenty klawiszowe",
  "Instrumenty elektroniczne",
  "Fortepian",
  "Skrzypce",
  "Gitara",
  "Flet",
  "Trąbka",
  "Perkusja",
  "Obój",
  "Klarnet",
  "Saksofon",
  "Wiolonczela",
  "Kontrabas",
  "Akordeon",
  "Organy",
  "Syntezator",
  "Tamburyn",
  "Marimba",
  "Ksylofon",
  "Bęben",
  "Kotły",
  "Gatunek rock",
  "Gatunek pop",
  "Gatunek jazz",
  "Gatunek blues",
  "Gatunek hip hop",
  "Gatunek klasyczny",
  "Gatunek elektroniczny",
  "Gatunek reggae",
  "Gatunek metal",
  "Gatunek soul",
  "Gatunek funk",
  "Gatunek disco",
  "Gatunek techno",
  "Gatunek house",
  "Gatunek trance",
  "Gatunek country",
  "Gatunek folk",
  "Gatunek gospel",
  "Gatunek punk",
  "Gatunek ambient",
  "Improwizacja",
  "Aranżacja",
  "Kompozycja",
  "Produkcja muzyczna",
  "Mixowanie",
  "Mastering",
  "Nagrywanie",
  "Wokal",
  "Chór",
  "Solista",
  "Duet",
  "Trio",
  "Kwintet",
  "Orkiestra",
  "Filharmonia",
  "Opera",
  "Operetka",
  "Musical",
  "Koncert",
  "Recital",
  "Festiwal",
  "Studio nagraniowe",
  "Scena",
  "Mikrofon",
  "Wzmacniacz",
  "Głośnik",
  "Słuchawki",
  "Płyta winylowa",
  "Kaseta magnetofonowa",
  "CD",
  "Streaming",
  "Radio",
  "Telewizja muzyczna",
  "Lista przebojów",
  "Hit",
  "Singiel",
  "Album",
  "EP",
  "Cover",
  "Remiks",
  "Teledysk",
  "Notacja muzyczna",
  "Pięciolinia",
  "Klucz wiolinowy",
  "Klucz basowy",
  "Nuta",
  "Pauza",
  "Metronom"
],
    Humor: [
  "Latający jamnik",
  "Parówka na patyku",
  "Kaczka w garniturze",
  "Ziemniak z brodą",
  "Kosmiczny kebab",
  "Tańczący banan",
  "Śpiewający ogórek",
  "Pies w okularach",
  "Krowa na deskorolce",
  "Kurczak ninja",
  "Brokuł z telefonem",
  "Szynka na trampolinie",
  "Sernik w kapeluszu",
  "Papryka z wąsami",
  "Delfin w skarpetkach",
  "Jeż w garniturze",
  "Pingwin na hulajnodze",
  "Cebula filozof",
  "Burak astronauta",
  "Marchewka detektyw",
  "Kaktus z gitarą",
  "Szczotka do zębów z osobowością",
  "Zegar z depresją",
  "Lampa z ADHD",
  "Kalosz z ambicjami",
  "Pomidorek influencer",
  "Frytka z doktoratem",
  "Mleko z tatuażem",
  "Tofu z ego",
  "Grzyb z planem na życie",
  "Korniszon z misją",
  "Słoik z marzeniami",
  "Kabanos z melancholią",
  "Szczur w smokingu",
  "Gołąb z GPS-em",
  "Pająk z lękiem wysokości",
  "Mysz z licencją pilota",
  "Biedronka z dyplomem MBA",
  "Żaba z paszportem",
  "Ślimak z zegarkiem",
  "Koń z laptopem",
  "Owca z podcastem",
  "Kura z blogiem kulinarnym",
  "Indyk z TikTokiem",
  "Bocian z CV",
  "Rekin z lękiem społecznym",
  "Wieloryb z fobią przed wodą",
  "Meduza z długiem studenckim",
  "Krab z obsesją na punkcie porządku",
  "Homar z rozterkami egzystencjalnymi",
  "Krewetka z planem biznesowym",
  "Ośmiornica z kalendarzem Google",
  "Sowa z problemem bezsenności",
  "Nietoperz z alergią na ciemność",
  "Wilk z lękiem przed samotnością",
  "Lis z kontem na LinkedIn",
  "Bóbr z obsesją na punkcie produktywności",
  "Żubr z kontem na OnlyFans",
  "Łoś z pasją do jogi",
  "Jeleń z tatuażem tribal",
  "Dzik z dietą keto",
  "Wiewiórka z planem emerytalnym",
  "Kret z latarką",
  "Struś z lękiem przed bieganiem",
  "Papuga z podcastem",
  "Kanarek z problemem komunikacyjnym",
  "Sroka z obsesją na punkcie błyskotek",
  "Wrona z blogiem o minimalizmie",
  "Orzeł z lękiem przed sukcesem",
  "Żart sytuacyjny",
  "Żart słowny",
  "Żart absurdalny",
  "Żart czarny",
  "Żart suchy",
  "Dowcip o blondynkach",
  "Dowcip o lekarzach",
  "Dowcip o politykach",
  "Dowcip o informatykach",
  "Dowcip o studentach",
  "Śmieszne powiedzonko",
  "Śmieszne porównanie",
  "Śmieszne skojarzenie",
  "Śmieszne nazwisko",
  "Śmieszne imię",
  "Komedia romantyczna",
  "Komedia kryminalna",
  "Komedia absurdalna",
  "Komedia familijna",
  "Komedia animowana",
  "Parodia filmowa",
  "Satyra polityczna",
  "Ironia sytuacyjna",
  "Sarkazm inteligentny",
  "Karykatura twarzy",
  "Mimika teatralna",
  "Gest komiczny",
  "Ruch sceniczny",
  "Gag wizualny",
  "Slapstick klasyczny",
  "One liner absurdalny",
  "Punchline zaskakujący",
  "Riposta szybka",
  "Kalambur logiczny",
  "Gra słów fonetyczna",
  "Dwuznaczność komiczna"
]
  },

  specjalistyczne: {
    Komputery: [
  "Procesor",
  "Pamięć RAM",
  "Dysk twardy",
  "Dysk SSD",
  "Karta graficzna",
  "Płyta główna",
  "Zasilacz",
  "Obudowa komputera",
  "Chłodzenie wodne",
  "Wentylator",
  "Monitor",
  "Klawiatura",
  "Mysz komputerowa",
  "Głośniki",
  "Słuchawki",
  "Mikrofon",
  "Kamera internetowa",
  "Router",
  "Modem",
  "Sieć Wi Fi",
  "Bluetooth",
  "Port USB",
  "Port HDMI",
  "Port Ethernet",
  "System operacyjny",
  "Windows",
  "Linux",
  "macOS",
  "Android",
  "iOS",
  "BIOS",
  "UEFI",
  "Sterownik",
  "Aktualizacja systemu",
  "Firewall",
  "Antywirus",
  "Ochrona danych",
  "Szyfrowanie",
  "Backup",
  "Chmura",
  "Serwer",
  "Hosting",
  "Domena internetowa",
  "Strona internetowa",
  "Przeglądarka",
  "Google Chrome",
  "Mozilla Firefox",
  "Microsoft Edge",
  "Opera",
  "Safari",
  "HTML",
  "CSS",
  "JavaScript",
  "Python",
  "C Plus Plus",
  "C Sharp",
  "Java",
  "PHP",
  "SQL",
  "Baza danych",
  "Algorytm",
  "Zmienna",
  "Funkcja",
  "Pętla",
  "Warunek",
  "Debugowanie",
  "Kompilacja",
  "IDE",
  "Git",
  "GitHub",
  "Repozytorium",
  "Commit",
  "Branch",
  "Merge",
  "Pull request",
  "Terminal",
  "Konsola",
  "Linia poleceń",
  "Skrypt",
  "Automatyzacja",
  "Sztuczna inteligencja",
  "Uczenie maszynowe",
  "Sieci neuronowe",
  "Big Data",
  "Internet rzeczy",
  "Rozszerzona rzeczywistość",
  "Wirtualna rzeczywistość",
  "Rozpoznawanie twarzy",
  "Asystent głosowy",
  "Chmura obliczeniowa",
  "Serwer dedykowany",
  "Serwer VPS",
  "Serwer NAS",
  "Sieć lokalna",
  "Sieć rozległa",
  "Adres IP",
  "Protokół TCP IP",
  "DNS",
  "VPN",
  "Tor",
  "Darknet",
  "Cyberbezpieczeństwo",
  "Phishing",
  "Malware",
  "Ransomware",
  "Trojan",
  "Historia komputerów",
  "Pierwszy komputer",
  "Komputer osobisty",
  "Laptop",
  "Tablet"
],
    Gazownictwo: [
  "Gazociąg wysokiego ciśnienia",
  "Gazociąg średniego ciśnienia",
  "Gazociąg niskiego ciśnienia",
  "Gazociąg przesyłowy",
  "Gazociąg rozdzielczy",
  "Instalacja gazowa wewnętrzna",
  "Instalacja gazowa zewnętrzna",
  "Instalacja odbiorcza",
  "Instalacja redukcyjna",
  "Instalacja pomiarowa",
  "Zawór kulowy",
  "Zawór zwrotny",
  "Zawór bezpieczeństwa",
  "Zawór odcinający",
  "Zawór regulacyjny",
  "Reduktor ciśnienia",
  "Stacja redukcyjno pomiarowa",
  "Stacja gazowa",
  "Stacja odbiorcza",
  "Stacja przesyłowa",
  "Przyłącze gazowe",
  "Przepust gazowy",
  "Przepływomierz",
  "Manometr",
  "Termometr gazowy",
  "Detektor gazu",
  "Czujnik metanu",
  "Czujnik propanu",
  "Czujnik tlenku węgla",
  "Czujnik ciśnienia",
  "Gazomierz miechowy",
  "Gazomierz rotorowy",
  "Gazomierz turbinowy",
  "Gazomierz ultradźwiękowy",
  "Gazomierz cieczowy",
  "Punkt redukcyjny",
  "Punkt pomiarowy",
  "Punkt odbioru",
  "Punkt kontrolny",
  "Punkt przyłączeniowy",
  "Sieć gazowa",
  "Sieć przesyłowa",
  "Sieć rozdzielcza",
  "Sieć dystrybucyjna",
  "Sieć lokalna",
  "Eksploatacja gazociągu",
  "Konserwacja instalacji",
  "Naprawa gazomierza",
  "Modernizacja sieci",
  "Rozbudowa infrastruktury",
  "Projekt gazowy",
  "Dokumentacja techniczna",
  "Mapa sytuacyjna",
  "Plan zagospodarowania",
  "Zgłoszenie przyłącza",
  "Pozwolenie na budowę",
  "Odbiór techniczny",
  "Próba szczelności",
  "Próba ciśnieniowa",
  "Próba wytrzymałości",
  "Próba eksploatacyjna",
  "Próba odbiorcza",
  "Bezpieczeństwo gazowe",
  "Instrukcja eksploatacji",
  "Instrukcja bezpieczeństwa",
  "Szkolenie gazowe",
  "Uprawnienia gazowe",
  "Operator gazowy",
  "Monter instalacji gazowej",
  "Projektant gazowy",
  "Inspektor nadzoru",
  "Ekspert ds gazownictwa",
  "Dyspozytor sieci",
  "Awaria gazowa",
  "Wycieki gazu",
  "Zatrucie gazem",
  "Ewakuacja budynku",
  "Zabezpieczenie terenu",
  "Gaz ziemny",
  "Gaz płynny",
  "Gaz syntetyczny",
  "Biogaz",
  "Propanu butan",
  "Metan",
  "Tlenek węgla",
  "Wodór",
  "Azot",
  "Spalanie gazu",
  "Kaloryczność gazu",
  "Wartość opałowa",
  "Emisja spalin",
  "Efektywność energetyczna",
  "Odnawialne źródła gazu",
  "Magazynowanie gazu",
  "Transport gazu",
  "Dystrybucja gazu",
  "Zużycie gazu",
  "Rozliczenie gazu",
  "Taryfa gazowa",
  "Faktura za gaz",
  "Umowa gazowa",
  "Prawo energetyczne",
  "Rozporządzenie gazowe",
  "Norma gazowa",
  "Certyfikat gazowy",
  "Audyt gazowy"
],
    Farmacja: [
  "Lek przeciwbólowy",
  "Lek przeciwgorączkowy",
  "Lek przeciwzapalny",
  "Lek przeciwwirusowy",
  "Lek przeciwbakteryjny",
  "Substancja czynna",
  "Substancja pomocnicza",
  "Substancja toksyczna",
  "Substancja lecznicza",
  "Substancja kontrolowana",
  "Receptor opioidowy",
  "Receptor serotoninowy",
  "Receptor dopaminowy",
  "Receptor histaminowy",
  "Receptor adrenergiczny",
  "Tabletka powlekana",
  "Tabletka musująca",
  "Tabletka do ssania",
  "Tabletka podjęzykowa",
  "Tabletka dopochwowa",
  "Kapsułka żelowa",
  "Kapsułka twarda",
  "Kapsułka miękka",
  "Kapsułka dojelitowa",
  "Kapsułka o przedłużonym uwalnianiu",
  "Maść lecznicza",
  "Maść przeciwbólowa",
  "Maść przeciwzapalna",
  "Maść sterydowa",
  "Maść dermatologiczna",
  "Krem farmaceutyczny",
  "Krem przeciwgrzybiczy",
  "Krem przeciwtrądzikowy",
  "Krem nawilżający",
  "Krem ochronny",
  "Syrop przeciwkaszlowy",
  "Syrop wykrztuśny",
  "Syrop dla dzieci",
  "Syrop ziołowy",
  "Syrop przeciwalergiczny",
  "Roztwór do wstrzykiwań",
  "Roztwór doustny",
  "Roztwór do infuzji",
  "Roztwór do płukania",
  "Roztwór do inhalacji",
  "Zawiesina doustna",
  "Zawiesina do oczu",
  "Zawiesina do nosa",
  "Zawiesina do ucha",
  "Zawiesina do wstrzykiwań",
  "Czopki doodbytnicze",
  "Czopki dopochwowe",
  "Czopki przeciwgorączkowe",
  "Czopki przeciwbólowe",
  "Czopki rozkurczowe",
  "Plaster leczniczy",
  "Plaster przeciwbólowy",
  "Plaster transdermalny",
  "Plaster nikotynowy",
  "Plaster hormonalny",
  "Aerozol do nosa",
  "Aerozol do gardła",
  "Aerozol do płuc",
  "Aerozol przeciwalergiczny",
  "Aerozol przeciwzapalny",
  "Krople do oczu",
  "Krople do nosa",
  "Krople do uszu",
  "Krople żołądkowe",
  "Krople uspokajające",
  "Ampułka do wstrzykiwań",
  "Ampułka do infuzji",
  "Ampułka z witaminą",
  "Ampułka z antybiotykiem",
  "Ampułka z insuliną",
  "Farmaceuta",
  "Technik farmaceutyczny",
  "Receptura apteczna",
  "Recepta lekarska",
  "Rejestracja leku",
  "Badanie kliniczne",
  "Interakcja leków",
  "Działanie niepożądane",
  "Biodostępność",
  "Biotransformacja",
  "Farmakokinetyka",
  "Farmakodynamika",
  "Toksykologia",
  "Antidotum",
  "Zatrucie lekami",
  "Przedawkowanie",
  "Monitorowanie terapii",
  "Opakowanie jednostkowe",
  "Opakowanie zbiorcze",
  "Numer serii",
  "Data ważności",
  "Przechowywanie leków",
  "Prawo farmaceutyczne",
  "Inspekcja farmaceutyczna",
  "Urząd rejestracji leków",
  "Narodowy Fundusz Zdrowia",
  "Refundacja leków",
  "Apteka ogólnodostępna",
  "Apteka szpitalna",
  "Apteka internetowa",
  "Apteka całodobowa",
  "Apteka zakładowa"
],
    Odpady: [
  "Odpady komunalne",
  "Odpady niebezpieczne",
  "Odpady medyczne",
  "Odpady przemysłowe",
  "Odpady budowlane",
  "Segregacja odpadów",
  "Segregacja u źródła",
  "Segregacja w zakładzie",
  "Segregacja mechaniczna",
  "Segregacja ręczna",
  "Recykling papieru",
  "Recykling plastiku",
  "Recykling szkła",
  "Recykling metali",
  "Recykling tekstyliów",
  "Kompostowanie",
  "Bioodpady",
  "Frakcja biodegradowalna",
  "Frakcja zmieszana",
  "Frakcja selektywna",
  "Punkt selektywnej zbiórki",
  "Punkt zbiórki elektroodpadów",
  "Punkt zbiórki baterii",
  "Punkt zbiórki odpadów niebezpiecznych",
  "Punkt zbiórki odpadów wielkogabarytowych",
  "Zbiórka odpadów",
  "Zbiórka mobilna",
  "Zbiórka stacjonarna",
  "Zbiórka sezonowa",
  "Zbiórka objazdowa",
  "Transport odpadów",
  "Logistyka odpadów",
  "Magazynowanie odpadów",
  "Składowanie odpadów",
  "Unieszkodliwianie odpadów",
  "Spalarnia odpadów",
  "Zakład przetwarzania",
  "Zakład recyklingu",
  "Zakład kompostowania",
  "Zakład segregacji",
  "Instalacja do odzysku",
  "Instalacja do unieszkodliwiania",
  "Instalacja do sortowania",
  "Instalacja do kompostowania",
  "Instalacja do spalania",
  "Katalog odpadów",
  "Kod odpadu",
  "Klasyfikacja odpadów",
  "Ewidencja odpadów",
  "Karta przekazania odpadu",
  "Decyzja środowiskowa",
  "Pozwolenie na zbieranie",
  "Pozwolenie na przetwarzanie",
  "Pozwolenie zintegrowane",
  "Zgłoszenie działalności odpadowej",
  "Ustawa o odpadach",
  "Rozporządzenie odpadowe",
  "Dyrektywa unijna",
  "Prawo środowiskowe",
  "Prawo gospodarki odpadami",
  "Gospodarka obiegu zamkniętego",
  "Zrównoważony rozwój",
  "Ekologiczne rozwiązania",
  "Odpowiedzialność producenta",
  "Opłata produktowa",
  "Opłata recyklingowa",
  "Opłata marszałkowska",
  "Raport środowiskowy",
  "Audyt odpadowy",
  "Sprawozdanie odpadowe",
  "Rejestr BDO",
  "Numer BDO",
  "Edukacja ekologiczna",
  "Kampania informacyjna",
  "Program selektywnej zbiórki",
  "Program recyklingu",
  "Program kompostowania",
  "Ślad węglowy",
  "Emisja gazów cieplarnianych",
  "Neutralność klimatyczna",
  "Odzysk energii",
  "Odzysk materiałowy",
  "Odzysk chemiczny",
  "Odzysk biologiczny",
  "Odzysk termiczny",
  "Tworzywa sztuczne",
  "Metale kolorowe",
  "Szkło opakowaniowe",
  "Papier makulaturowy",
  "Baterie i akumulatory",
  "Sprzęt elektryczny",
  "Sprzęt elektroniczny",
  "Zużyte opony",
  "Odpady zielone",
  "Odpady kuchenne",
  "Odpady z remontów",
  "Odpady z ogrodu",
  "Odpady z biura",
  "Odpady z gastronomii",
  "Odpady z rolnictwa",
  "Odpady z przemysłu",
  "Odpady z edukacji",
  "Odpady z transportu",
  "Odpady z handlu"
],
    Biznes: [
  "Zarządzanie strategiczne",
  "Zarządzanie operacyjne",
  "Zarządzanie projektami",
  "Zarządzanie ryzykiem",
  "Zarządzanie zmianą",
  "Strategia rozwoju",
  "Strategia marketingowa",
  "Strategia finansowa",
  "Strategia komunikacyjna",
  "Strategia ESG",
  "Audyt wewnętrzny",
  "Audyt zewnętrzny",
  "Audyt finansowy",
  "Audyt operacyjny",
  "Audyt zgodności",
  "Komunikacja korporacyjna",
  "Komunikacja kryzysowa",
  "Komunikacja wewnętrzna",
  "Komunikacja z interesariuszami",
  "Komunikacja międzykulturowa",
  "Kultura organizacyjna",
  "Struktura hierarchiczna",
  "Struktura macierzowa",
  "Struktura płaska",
  "Struktura funkcjonalna",
  "Ład korporacyjny",
  "Kodeks etyki",
  "Misja firmy",
  "Wizja firmy",
  "Wartości korporacyjne",
  "Zarząd spółki",
  "Rada nadzorcza",
  "Walne zgromadzenie",
  "Akcjonariusz",
  "Spółka akcyjna",
  "Spółka z ograniczoną odpowiedzialnością",
  "Spółka komandytowa",
  "Spółka jawna",
  "Holding",
  "Konsorcjum",
  "Fuzja",
  "Przejęcie",
  "Joint venture",
  "Due diligence",
  "Compliance",
  "Polityka antykorupcyjna",
  "Polityka różnorodności",
  "Polityka prywatności",
  "Polityka wynagrodzeń",
  "Polityka zakupowa",
  "Zarządzanie talentami",
  "Zarządzanie kompetencjami",
  "Zarządzanie efektywnością",
  "Zarządzanie konfliktem",
  "Zarządzanie zespołem",
  "Rekrutacja",
  "Onboarding",
  "Employer branding",
  "Ocena pracownicza",
  "Szkolenie korporacyjne",
  "Rozwój zawodowy",
  "Ścieżka kariery",
  "Motywacja pracowników",
  "Benefity pracownicze",
  "Outsourcing",
  "Offshoring",
  "Insourcing",
  "Benchmarking",
  "Lean management",
  "Six Sigma",
  "Agile",
  "Scrum",
  "Kanban",
  "Budżet operacyjny",
  "Budżet inwestycyjny",
  "Budżet marketingowy",
  "Budżet HR",
  "Budżet IT",
  "Raport roczny",
  "Raport kwartalny",
  "Raport ESG",
  "Raport finansowy",
  "Raport zarządu",
  "Analiza SWOT",
  "Analiza PEST",
  "Analiza konkurencji",
  "Analiza rynku",
  "Analiza kosztów",
  "Rentowność",
  "Płynność finansowa",
  "Zysk netto",
  "EBITDA",
  "ROI",
  "Cash flow",
  "Kapitał własny",
  "Kapitał obrotowy",
  "Zobowiązania",
  "Aktywa trwałe",
  "Aktywa obrotowe",
  "Wskaźnik zadłużenia",
  "Wskaźnik rentowności",
  "Wskaźnik płynności",
  "Wskaźnik rotacji zapasów",
  "Wskaźnik efektywności"
],
    Astronomia: [
  "Układ słoneczny",
  "Słońce",
  "Księżyc",
  "Ziemia",
  "Merkury",
  "Wenus",
  "Mars",
  "Jowisz",
  "Saturn",
  "Uran",
  "Neptun",
  "Pluton",
  "Planeta karłowata",
  "Planeta gazowa",
  "Planeta skalista",
  "Planeta pozasłoneczna",
  "Gwiazda neutronowa",
  "Gwiazda podwójna",
  "Gwiazda zmienna",
  "Gwiazda olbrzym",
  "Gwiazda supernowa",
  "Galaktyka spiralna",
  "Galaktyka eliptyczna",
  "Galaktyka nieregularna",
  "Galaktyka karłowata",
  "Galaktyka aktywna",
  "Droga Mleczna",
  "Andromeda",
  "Mgławica planetarna",
  "Mgławica emisyjna",
  "Mgławica refleksyjna",
  "Mgławica ciemna",
  "Mgławica Kraba",
  "Czarna dziura",
  "Biała dziura",
  "Kwazar",
  "Pulsar",
  "Supernowa",
  "Kometa",
  "Asteroida",
  "Meteoryt",
  "Meteor",
  "Pas Kuipera",
  "Obłok Oorta",
  "Zjawisko zaćmienia",
  "Zaćmienie Słońca",
  "Zaćmienie Księżyca",
  "Tranzyt Merkurego",
  "Tranzyt Wenus",
  "Konjunkcja planet",
  "Opozycja planet",
  "Ruch obiegowy",
  "Ruch obrotowy",
  "Grawitacja",
  "Grawitacja pływowa",
  "Grawitacja planetarna",
  "Grawitacja gwiazdowa",
  "Grawitacja galaktyczna",
  "Promieniowanie kosmiczne",
  "Promieniowanie gamma",
  "Promieniowanie rentgenowskie",
  "Promieniowanie podczerwone",
  "Promieniowanie radiowe",
  "Spektrum elektromagnetyczne",
  "Spektrum widzialne",
  "Spektrum absorpcyjne",
  "Spektrum emisyjne",
  "Spektrum ciągłe",
  "Czerwony przesunięcie",
  "Niebieski przesunięcie",
  "Ekspansja Wszechświata",
  "Wielki Wybuch",
  "Inflacja kosmiczna",
  "Ciemna materia",
  "Ciemna energia",
  "Stała Hubble’a",
  "Teleskop optyczny",
  "Teleskop radiowy",
  "Teleskop kosmiczny",
  "Teleskop Hubble’a",
  "Teleskop Jamesa Webba",
  "Obserwatorium astronomiczne",
  "Obserwatorium naziemne",
  "Obserwatorium orbitalne",
  "Misja Voyager",
  "Misja Cassini",
  "Misja Galileo",
  "Misja New Horizons",
  "Misja Rosetta",
  "Misja Juno",
  "Misja Artemis",
  "Misja Apollo",
  "Misja Curiosity",
  "Misja Perseverance",
  "Międzynarodowa Stacja Kosmiczna",
  "Kosmodrom Bajkonur",
  "Kosmodrom Cape Canaveral",
  "Astronauta",
  "Kosmonauta",
  "Astrofizyka",
  "Kosmologia",
  "Mechanika nieba",
  "Orbita geostacjonarna",
  "Orbita heliocentryczna",
  "Orbita eliptyczna"
],
    Sport: [
  "Piłka nożna",
  "Piłka ręczna",
  "Piłka siatkowa",
  "Piłka koszykowa",
  "Piłka wodna",
  "Bieg na sto metrów",
  "Bieg przez płotki",
  "Bieg maratoński",
  "Bieg przełajowy",
  "Bieg sztafetowy",
  "Skok wzwyż",
  "Skok w dal",
  "Skok o tyczce",
  "Skok do wody",
  "Skok narciarski",
  "Rzut oszczepem",
  "Rzut młotem",
  "Rzut dyskiem",
  "Rzut piłką",
  "Rzut wolny",
  "Pływanie stylem dowolnym",
  "Pływanie stylem klasycznym",
  "Pływanie stylem motylkowym",
  "Pływanie stylem grzbietowym",
  "Pływanie synchroniczne",
  "Szermierka",
  "Łucznictwo",
  "Strzelectwo sportowe",
  "Podnoszenie ciężarów",
  "Gimnastyka artystyczna",
  "Gimnastyka sportowa",
  "Gimnastyka akrobatyczna",
  "Jazda na rowerze",
  "Kolarstwo szosowe",
  "Kolarstwo górskie",
  "Kolarstwo torowe",
  "Kolarstwo BMX",
  "Tenis ziemny",
  "Tenis stołowy",
  "Badminton",
  "Squash",
  "Golf",
  "Hokej na lodzie",
  "Hokej na trawie",
  "Curling",
  "Snowboard",
  "Narciarstwo alpejskie",
  "Narciarstwo biegowe",
  "Narciarstwo dowolne",
  "Biathlon",
  "Saneczkarstwo",
  "Bobsleje",
  "Skeleton",
  "Wioślarstwo",
  "Kajakarstwo",
  "Żeglarstwo",
  "Żeglarstwo regatowe",
  "Żeglarstwo oceaniczne",
  "Windsurfing",
  "Kitesurfing",
  "Surfing",
  "Triathlon",
  "Duathlon",
  "Pięciobój nowoczesny",
  "Pięciobój klasyczny",
  "Zapasy",
  "Judo",
  "Karate",
  "Taekwondo",
  "Boks",
  "Kickboxing",
  "Mieszane sztuki walki",
  "Sumo",
  "Wspinaczka sportowa",
  "Wspinaczka na czas",
  "Wspinaczka boulderowa",
  "Wspinaczka z liną",
  "Parkour",
  "Jeździectwo",
  "Ujeżdżenie",
  "Skoki przez przeszkody",
  "WKKW",
  "Wyścigi konne",
  "Wyścigi samochodowe",
  "Wyścigi motocyklowe",
  "Rajdy terenowe",
  "Formuła jeden",
  "Drifting",
  "Sporty ekstremalne",
  "Sporty drużynowe",
  "Sporty indywidualne",
  "Sporty wodne",
  "Sporty zimowe",
  "Sporty letnie",
  "Sporty halowe",
  "Sporty na świeżym powietrzu",
  "Trening siłowy",
  "Trening wytrzymałościowy",
  "Trening interwałowy",
  "Trening funkcjonalny",
  "Trening mentalny",
  "Rozgrzewka",
  "Regeneracja",
  "Motywacja sportowa",
  "Rywalizacja",
  "Fair play"
],
    Sztuka: [
  "Malarstwo olejne",
  "Malarstwo akwarelowe",
  "Malarstwo temperowe",
  "Malarstwo ścienne",
  "Malarstwo abstrakcyjne",
  "Rzeźba w kamieniu",
  "Rzeźba w drewnie",
  "Rzeźba w metalu",
  "Rzeźba nowoczesna",
  "Rzeźba klasyczna",
  "Architektura gotycka",
  "Architektura romańska",
  "Architektura barokowa",
  "Architektura modernistyczna",
  "Architektura współczesna",
  "Styl impresjonistyczny",
  "Styl ekspresjonistyczny",
  "Styl surrealistyczny",
  "Styl kubistyczny",
  "Styl renesansowy",
  "Technika kolażu",
  "Technika linorytu",
  "Technika drzeworytu",
  "Technika fresku",
  "Technika mozaiki",
  "Artysta malarz",
  "Artysta rzeźbiarz",
  "Artysta grafik",
  "Artysta fotograf",
  "Artysta konceptualny",
  "Dzieło sztuki",
  "Instalacja artystyczna",
  "Obraz olejny",
  "Obraz abstrakcyjny",
  "Obraz realistyczny",
  "Portret",
  "Autoportret",
  "Martwa natura",
  "Pejzaż",
  "Akt",
  "Wystawa sztuki",
  "Galeria sztuki",
  "Muzeum sztuki",
  "Biennale",
  "Targi sztuki",
  "Krytyka artystyczna",
  "Historia sztuki",
  "Teoria sztuki",
  "Estetyka",
  "Symbolika w sztuce",
  "Perspektywa linearna",
  "Perspektywa powietrzna",
  "Kompozycja obrazu",
  "Kolorystyka",
  "Światłocień",
  "Faktura malarska",
  "Forma przestrzenna",
  "Rytm wizualny",
  "Kontrast",
  "Harmonia",
  "Dynamika",
  "Minimalizm",
  "Ekspresja",
  "Dekonstrukcja",
  "Postmodernizm",
  "Nowe media",
  "Sztuka cyfrowa",
  "Sztuka uliczna",
  "Sztuka konceptualna",
  "Sztuka performatywna",
  "Performance",
  "Happening",
  "Body art",
  "Land art",
  "Video art",
  "Fotografia analogowa",
  "Fotografia cyfrowa",
  "Fotografia portretowa",
  "Fotografia reportażowa",
  "Fotografia artystyczna",
  "Film eksperymentalny",
  "Film animowany",
  "Film dokumentalny",
  "Film fabularny",
  "Film krótkometrażowy",
  "Teatr dramatyczny",
  "Teatr muzyczny",
  "Teatr alternatywny",
  "Teatr lalek",
  "Teatr tańca",
  "Taniec współczesny",
  "Taniec klasyczny",
  "Taniec ludowy",
  "Taniec nowoczesny",
  "Taniec uliczny",
  "Design graficzny",
  "Design przemysłowy",
  "Design wnętrz",
  "Design mody",
  "Design użytkowy",
  "Plakat artystyczny",
  "Ilustracja",
  "Typografia",
  "Książka artystyczna",
  "Zine"
],
    Transport: [
  "Transport drogowy",
  "Transport kolejowy",
  "Transport lotniczy",
  "Transport wodny",
  "Transport intermodalny",
  "Pojazd elektryczny",
  "Pojazd spalinowy",
  "Pojazd hybrydowy",
  "Pojazd autonomiczny",
  "Pojazd ciężarowy",
  "Samochód osobowy",
  "Samochód dostawczy",
  "Samochód terenowy",
  "Samochód sportowy",
  "Samochód zabytkowy",
  "Motocykl",
  "Skuter",
  "Rower miejski",
  "Rower elektryczny",
  "Rower cargo",
  "Tramwaj",
  "Metro",
  "Pociąg ekspresowy",
  "Pociąg regionalny",
  "Pociąg towarowy",
  "Autobus miejski",
  "Autobus dalekobieżny",
  "Autobus elektryczny",
  "Autobus przegubowy",
  "Autobus autonomiczny",
  "Ciężarówka",
  "Tir",
  "Cysterna",
  "Laweta",
  "Furgonetka",
  "Samolot pasażerski",
  "Samolot towarowy",
  "Samolot wojskowy",
  "Samolot odrzutowy",
  "Samolot śmigłowy",
  "Helikopter",
  "Dron transportowy",
  "Sterowiec",
  "Statek pasażerski",
  "Statek towarowy",
  "Prom",
  "Łódź motorowa",
  "Łódź wiosłowa",
  "Jacht",
  "Kajak",
  "Kanoe",
  "Kontener",
  "Paleta transportowa",
  "Naczepa",
  "Przyczepa",
  "Wózek widłowy",
  "Terminal kontenerowy",
  "Port lotniczy",
  "Port morski",
  "Dworzec kolejowy",
  "Zajezdnia autobusowa",
  "Stacja paliw",
  "Stacja ładowania",
  "Stacja kontroli pojazdów",
  "Stacja rozładunkowa",
  "Droga ekspresowa",
  "Droga krajowa",
  "Droga wojewódzka",
  "Droga powiatowa",
  "Droga gminna",
  "Autostrada",
  "Obwodnica",
  "Rondo",
  "Skrzyżowanie",
  "Sygnalizacja świetlna",
  "Przejście dla pieszych",
  "Przejazd kolejowy",
  "Tunel drogowy",
  "Most wiszący",
  "Most łukowy",
  "Most zwodzony",
  "Most kolejowy",
  "Logistyka miejska",
  "Logistyka magazynowa",
  "Logistyka transportowa",
  "Logistyka zwrotna",
  "Logistyka ekologiczna",
  "Bezpieczeństwo ruchu drogowego",
  "Bezpieczeństwo pasażerów",
  "Bezpieczeństwo przewozu towarów",
  "Bezpieczeństwo na lotnisku",
  "Bezpieczeństwo w porcie",
  "Ekologia transportu",
  "Emisja spalin",
  "Hałas komunikacyjny",
  "Zrównoważony transport",
  "Mobilność miejska",
  "Historia kolei",
  "Historia lotnictwa",
  "Historia motoryzacji",
  "Historia żeglugi",
  "Historia transportu publicznego"
],
    Kuchnia: [
  "Zupa pomidorowa",
  "Zupa ogórkowa",
  "Zupa grzybowa",
  "Zupa krem z dyni",
  "Zupa cebulowa",
  "Mięso wołowe",
  "Mięso wieprzowe",
  "Mięso drobiowe",
  "Mięso mielone",
  "Mięso duszone",
  "Ryba smażona",
  "Ryba pieczona",
  "Ryba w galarecie",
  "Ryba grillowana",
  "Ryba wędzona",
  "Makaron spaghetti",
  "Makaron penne",
  "Makaron tagliatelle",
  "Makaron ryżowy",
  "Makaron pełnoziarnisty",
  "Ryż biały",
  "Ryż brązowy",
  "Ryż jaśminowy",
  "Ryż basmati",
  "Ryż arborio",
  "Ziemniaki gotowane",
  "Ziemniaki pieczone",
  "Ziemniaki smażone",
  "Ziemniaki z wody",
  "Ziemniaki z ogniska",
  "Sałatka jarzynowa",
  "Sałatka grecka",
  "Sałatka z kurczakiem",
  "Sałatka z tuńczykiem",
  "Sałatka z serem feta",
  "Pieczywo pszenne",
  "Pieczywo żytnie",
  "Pieczywo razowe",
  "Pieczywo bezglutenowe",
  "Pieczywo tostowe",
  "Ser żółty",
  "Ser biały",
  "Ser pleśniowy",
  "Ser kozi",
  "Ser mozzarella",
  "Jajka na twardo",
  "Jajka na miękko",
  "Jajka sadzone",
  "Jajka w koszulce",
  "Jajka faszerowane",
  "Przyprawa curry",
  "Przyprawa papryka",
  "Przyprawa bazylia",
  "Przyprawa oregano",
  "Przyprawa tymianek",
  "Olej rzepakowy",
  "Olej słonecznikowy",
  "Olej kokosowy",
  "Olej sezamowy",
  "Olej lniany",
  "Masło klarowane",
  "Masło zwykłe",
  "Margaryna",
  "Śmietana kwaśna",
  "Śmietana słodka",
  "Cukier biały",
  "Cukier brązowy",
  "Cukier puder",
  "Cukier trzcinowy",
  "Cukier waniliowy",
  "Mąka pszenna",
  "Mąka żytnia",
  "Mąka kukurydziana",
  "Mąka ziemniaczana",
  "Mąka ryżowa",
  "Nóż kuchenny",
  "Nóż do chleba",
  "Nóż do mięsa",
  "Nóż do warzyw",
  "Nóż szefa kuchni",
  "Garnek emaliowany",
  "Garnek stalowy",
  "Garnek ceramiczny",
  "Garnek żeliwny",
  "Garnek do gotowania na parze",
  "Patelnia teflonowa",
  "Patelnia ceramiczna",
  "Patelnia grillowa",
  "Patelnia żeliwna",
  "Patelnia do naleśników",
  "Deska do krojenia",
  "Tarka do warzyw",
  "Mikser ręczny",
  "Blender kielichowy",
  "Robot kuchenny",
  "Piekarnik elektryczny",
  "Piekarnik gazowy",
  "Kuchenka indukcyjna",
  "Kuchenka gazowa",
  "Kuchenka mikrofalowa",
  "Kuchnia włoska",
  "Kuchnia francuska",
  "Kuchnia polska",
  "Kuchnia azjatycka",
  "Kuchnia meksykańska"
]
  }
};

// 🔷 Zmienne globalne
let haslo = "";
let dlugosc = 0;
let ile_skuch = 0;
let haslo1 = "";
let aktualnaKategoria = "";
let aktualnyTyp = "";

// 🔷 Pokaz ekran wyboru kategorii
function pokazWyborKategorii() {
  document.getElementById("start").style.display = "none";
  document.getElementById("wybor-kategorii").style.display = "block";
  wypelnijKategorie();
}

// 🔷 Wypełnij przyciski kategorii
function wypelnijKategorie() {
  const klasyczneDiv = document.getElementById("klasyczne-kategorie");
  const specjalistyczneDiv = document.getElementById("specjalistyczne-kategorie");
  klasyczneDiv.innerHTML = "";
  specjalistyczneDiv.innerHTML = "";

  for (const nazwa in bazaDanych.klasyczne) {
    const btn = document.createElement("button");
    btn.textContent = nazwa;
    btn.className = "przycisk-kategorii";
    btn.onclick = () => rozpocznijGreZKategoria(nazwa, "klasyczne");
    klasyczneDiv.appendChild(btn);
  }

  for (const nazwa in bazaDanych.specjalistyczne) {
    const btn = document.createElement("button");
    btn.textContent = nazwa;
    btn.className = "przycisk-kategorii";
    btn.onclick = () => rozpocznijGreZKategoria(nazwa, "specjalistyczne");
    specjalistyczneDiv.appendChild(btn);
  }
}

// 🔷 Rozpocznij grę z wybraną kategorią
function rozpocznijGreZKategoria(nazwa, typ) {
  aktualnaKategoria = nazwa;
  aktualnyTyp = typ;
  const bazaHasel = bazaDanych[typ][nazwa];
  haslo = bazaHasel[Math.floor(Math.random() * bazaHasel.length)].toUpperCase();
  dlugosc = haslo.length;
  ile_skuch = 0;
  haslo1 = "";

  for (let i = 0; i < dlugosc; i++) {
    haslo1 += haslo.charAt(i) === " " ? " " : "-";
  }

  document.getElementById("wybor-kategorii").style.display = "none";
  document.getElementById("pojemnik").style.display = "block";
  document.getElementById("kategoria-info").innerHTML =
    '<span style="color:#00C000;">Kategoria:</span> ' + nazwa;
  document.getElementById("szubienica").innerHTML = '<img src="s0.jpg" alt="" />';
  start();
  window.scrollTo({
  top: 0,
  behavior: 'smooth' // możesz też użyć 'auto' dla natychmiastowego scrolla
});

}

// 🔷 Restart gry z tą samą kategorią
function restart() {
  const bazaHasel = bazaDanych[aktualnyTyp][aktualnaKategoria];
  haslo = bazaHasel[Math.floor(Math.random() * bazaHasel.length)].toUpperCase();
  dlugosc = haslo.length;
  ile_skuch = 0;
  haslo1 = "";

  for (let i = 0; i < dlugosc; i++) {
    haslo1 += haslo.charAt(i) === " " ? " " : "-";
  }

  document.getElementById("kategoria-info").innerHTML =
    '<span style="color:#00C000;">Kategoria:</span> ' + aktualnaKategoria;
  document.getElementById("szubienica").innerHTML = '<img src="s0.jpg" alt="" />';
  document.getElementById("alfabet").innerHTML = "";
  start();
}

// 🔷 Powrót do wyboru kategorii
function powrotDoWyboru() {
  document.getElementById("pojemnik").style.display = "none";
  document.getElementById("wybor-kategorii").style.display = "block";
}

// 🔷 Inicjalizacja po załadowaniu strony
window.addEventListener("DOMContentLoaded", function () {
  wypelnijKategorie();
});

		//haslo = baza[Math.floor(Math.random()*baza.length)]
		
/*var losowa = Math.floor((Math.random() *6 +1));

if (losowa <= 1){
	haslo = "Dupa blada"

} else if(losowa === 1){
	haslo = "Pieniądze to nie wszystko"

} else if (losowa === 2){
	haslo = "Tolerancja jest córką wątpliwości"

} else if (losowa === 3){
	haslo = "Od nędzy do pieniędzy"

} else if (losowa === 4){
	haslo = "Miałeś chamie złoty róg"

} else if (losowa === 5){
	haslo = "I bym teraz kurwa nie miał ręki"

} else if (losowa === 6){
	haslo = "To ludzie ludziom zgotowali ten los"

}
  else {
	haslo = "Dlaczego ja"
}
*/
//console.log(losowa);
console.log(haslo)

haslo = haslo.toUpperCase();




//var motyw = new Audio("motyw.wav")
var win = new Audio("win.wav");
var boo = new Audio("boo.wav");
var yes = new Audio("yes.wav");
var no = new Audio("no.wav");


for (i=0; i<dlugosc; i++)
{
	if (haslo.charAt(i)==" ") haslo1 = haslo1 + " ";
	else haslo1 = haslo1 + "-";
}

function wypisz_haslo()
{
	document.getElementById("plansza").innerHTML = haslo1;
}

//window.onload = start;

var litery = new Array(35);

litery[0] = "A";
litery[1] = "Ą";
litery[2] = "B";
litery[3] = "C";
litery[4] = "Ć";
litery[5] = "D";
litery[6] = "E";
litery[7] = "Ę";
litery[8] = "F";
litery[9] = "G";
litery[10] = "H";
litery[11] = "I";
litery[12] = "J";
litery[13] = "K";
litery[14] = "L";
litery[15] = "Ł";
litery[16] = "M";
litery[17] = "N";
litery[18] = "Ń";
litery[19] = "O";
litery[20] = "Ó";
litery[21] = "P";
litery[22] = "Q";
litery[23] = "R";
litery[24] = "S";
litery[25] = "Ś";
litery[26] = "T";
litery[27] = "U";
litery[28] = "V";
litery[29] = "W";
litery[30] = "X";
litery[31] = "Y";
litery[32] = "Z";
litery[33] = "Ż";
litery[34] = "Ź";



function start()
{
	
	var tresc_diva ="";
	
	for (i=0; i<=34; i++)
	{
		var element = "lit" + i;
		tresc_diva = tresc_diva + '<div class="litera" onclick="sprawdz('+i+')" id="'+element+'">'+litery[i]+'</div>';
		if ((i+1) % 7 ==0) tresc_diva = tresc_diva + '<div style="clear:both;"></div>';
	}
	
	document.getElementById("alfabet").innerHTML = tresc_diva;
	
	
	wypisz_haslo();
}

String.prototype.ustawZnak = function(miejsce, znak)
{
	if (miejsce > this.length - 1) return this.toString();
	else return this.substr(0, miejsce) + znak + this.substr(miejsce+1);
}


function sprawdz(nr)
{
	
	var trafiona = false;
	
	for(i=0; i<dlugosc; i++)
	{
		if (haslo.charAt(i) == litery[nr]) 
		{
			haslo1 = haslo1.ustawZnak(i,litery[nr]);
			trafiona = true;
		}
	}
	
	if(trafiona == true)
	{
		yes.play();
		var element = "lit" + nr;
		document.getElementById(element).style.background = "#003300";
		document.getElementById(element).style.color = "#00C000";
		document.getElementById(element).style.border = "3px solid #00C000";
		document.getElementById(element).style.cursor = "default";
		
		wypisz_haslo();
	}
	else
	{
		no.play();
		var element = "lit" + nr;
		document.getElementById(element).style.background = "#330000";
		document.getElementById(element).style.color = "#C00000";
		document.getElementById(element).style.border = "3px solid #C00000";
		document.getElementById(element).style.cursor = "default";	
		document.getElementById(element).setAttribute("onclick",";");		
		
		//skucha
		ile_skuch++;
		var obraz = "s"+ ile_skuch + ".jpg";
		document.getElementById("szubienica").innerHTML = '<img src="'+obraz+'" alt="" />';
	}
	
	//wygrana
	if (haslo == haslo1){
	document.getElementById("alfabet").innerHTML  = '<span style="color: green">Tak jest! Podano prawidłowe hasło: </span>'+haslo+'<br /><br /><span class="reset" onclick="restart()">JESZCZE RAZ?</span>';
	win.play();
}
	//przegrana
	if (ile_skuch>=9){
	document.getElementById("alfabet").innerHTML  = '<span style="color: red">Przegrana! Nieprawidłowe hasło!<br> </span><br /><br /><span class="reset" onclick="restart()">JESZCZE RAZ?</span>';
	boo.play();
}
}